### ISSUE TITLE
Failed to push to gh-pages

### ISSUE THREAD

**Issue by ghost** [online-judge-tools/verification-helper#412] opened 2023-04-04 05:40 UTC
## Summary / 概要

This is what it shows up on the workflow.

## Actual behavior / 実際の挙動

``` console
ERROR:onlinejudge_verify.main:GH_PAT is not available. You cannot upload the generated documents to GitHub Pages.
INFO:onlinejudge_verify.verify:all tests succeeded
```

## Other notes / その他

-   Will you try to create a pull request?
    -   no

**Comment by koba-e964** [comment] 2023-12-08 00:34
Couldn't reproduce. Closing

**Closed by koba-e964** 2023-12-08 00:34 UTC
